#!/bin/bash

echo "🔍 Finding IP Addresses for MongoDB Atlas Whitelist"
echo "=================================================="

echo ""
echo "📋 Current Options:"
echo ""
echo "1. 🌐 Allow All IPs (Recommended for Development):"
echo "   - Go to MongoDB Atlas → Network Access"
echo "   - Add IP Address: 0.0.0.0/0"
echo "   - Comment: 'Allow all IPs for development'"
echo ""
echo "2. 💰 Vercel Static IPs (Paid Feature):"
echo "   - Upgrade to Vercel Pro/Enterprise"
echo "   - Enable Static IPs feature"
echo "   - Get static IP addresses from Vercel dashboard"
echo "   - Add those IPs to MongoDB Atlas"
echo ""
echo "3. 🔧 Render Static IPs:"
echo "   - Contact Render support for static IP options"
echo "   - Or use 0.0.0.0/0 for development"
echo ""
echo "4. 🧪 Test Current IPs:"
echo "   - Deploy your app to Render/Vercel"
echo "   - Check the logs for outbound IP"
echo "   - Or use a service like ipify.org"
echo ""

# Create a simple IP detection endpoint for your backend
echo "📝 Add this to your backend to detect IP:"
echo ""
echo "// Add to server.js for IP detection"
echo "app.get('/api/ip', (req, res) => {"
echo "  const ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress;"
echo "  res.json({ ip: ip });"
echo "});"
echo ""
echo "Then call: curl https://your-app.onrender.com/api/ip"
echo ""

echo "🎯 Recommended Action:"
echo "For development: Use 0.0.0.0/0 (allow all IPs)"
echo "For production: Consider Vercel Static IPs or strong authentication"

